<?xml version="1.0"?>
<robot name="scout_v2" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="scout_v2">
    <!-- Variables -->
    <xacro:property name="M_PI" value="3.1415926"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.9250000"/>
    <xacro:property name="base_y_size" value="0.380000"/>
    <xacro:property name="base_z_size" value="0.210000"/>

    <xacro:property name="wheelbase" value="0.498"/>
    <xacro:property name="track" value="0.58306"/>
    <xacro:property name="wheel_vertical_offset" value="-0.0702"/>

    <xacro:property name="wheel_length" value="1.1653e-01"/>
    <xacro:property name="wheel_radius" value="1.6459e-01"/>

    <!-- base footprint -->
    <link name="base_footprint"/>
    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 0.23" rpy="0 0 0"/>
      <parent link="base_footprint"/>
      <child link="base_link"/>
    </joint>

    <!-- base link -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://scout_description/meshes/base_link.dae"/>
        </geometry>
      </visual>
      <inertial>
        <origin xyz="0 0 0.5" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="100"  ixy="0"  ixz="0" iyy="100" iyz="0" izz="100" />
      </inertial>
      <collision>
        <origin xyz="0 0 0.008" rpy="0 0 0"/>
        <geometry>
          <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 ${base_z_size/6}" rpy="0 0 0"/>
        <geometry>
          <box size="${base_x_size/6} ${base_y_size*1.65} ${base_z_size/3}"/>
        </geometry>
      </collision>
    </link>

    <!-- mid mount -->
    <link name="mid_mount"/>
    <joint name="mid_mount_joint" type="fixed">
      <origin xyz="0 0 0.113" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="mid_mount"/>
    </joint>

    <!-- front left -->
    <link name="front_left_wheel_link">
      <inertial>
        <mass value="3"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://scout_description/meshes/wheel_type2.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
    </link>
    <joint name="front_left_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="front_left_wheel_link"/>
      <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0" rpy="0 0 0"/>
    </joint>

    <transmission name="tran_front_left">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="front_left_wheel">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor_front_left">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <!-- rear left -->
    <link name="rear_left_wheel_link">
      <inertial>
        <mass value="3"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
	        <mesh filename="package://scout_description/meshes/wheel_type1.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
	        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
    </link>
    <joint name="rear_left_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="rear_left_wheel_link"/>
      <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0" rpy="0 0 0"/>
    </joint>

    <transmission name="tran_rear_left">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="rear_left_wheel">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor_rear_left">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <!-- front right -->
    <link name="front_right_wheel_link">
      <inertial>
        <mass value="3"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${M_PI}"/>
        <geometry>
	        <mesh filename="package://scout_description/meshes/wheel_type1.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
	        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
    </link>
    <joint name="front_right_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="front_right_wheel_link"/>
      <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0" rpy="0 0 0"/>
    </joint>

    <transmission name="tran_front_right">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="front_right_wheel">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor_front_right">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <!-- rear right -->
    <link name="rear_right_wheel_link">
      <inertial>
        <mass value="3"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${M_PI}"/>
        <geometry>
	        <mesh filename="package://scout_description/meshes/wheel_type2.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
	        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
    </link>
    <joint name="rear_right_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="rear_right_wheel_link"/>
      <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0" rpy="0 0 0"/>
    </joint>

    <transmission name="tran_rear_right">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="rear_right_wheel">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor_rear_right">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>
</robot>
